import {DatePipe} from '@angular/common';import{Component,DestroyRef,OnInit,inject,signal}from'@angular/core';import{takeUntilDestroyed}from'@angular/core/rxjs-interop';
import{FormBuilder,ReactiveFormsModule}from'@angular/forms';import{MatButtonModule}from'@angular/material/button';import{MatDialog,MatDialogModule}from'@angular/material/dialog';import{MatFormFieldModule}from'@angular/material/form-field';import{MatSelectModule}from'@angular/material/select';import{MatPaginatorModule,PageEvent}from'@angular/material/paginator';import{MatProgressBarModule}from'@angular/material/progress-bar';import{MatSortModule,Sort}from'@angular/material/sort';import{MatTableModule}from'@angular/material/table';import{Subject,filter,switchMap,of,tap,finalize}from'rxjs';
import{AlertStatus,FraudAlert}from'./alert.models';import{AlertService}from'./alert.service';import{AlertActionDialogComponent}from'./alert-action-dialog.component';
@Component({selector:'app-alert-queue',standalone:true,imports:[DatePipe,ReactiveFormsModule,MatButtonModule,MatDialogModule,MatFormFieldModule,MatSelectModule,MatPaginatorModule,MatProgressBarModule,MatSortModule,MatTableModule],
template:`<section class="page"><header><div><p>FRAUD OPERATIONS</p><h1 class="page-title">Alert Queue</h1><span>Prioritized investigation workload and SLA control.</span></div></header>
<form [formGroup]="filters"><mat-form-field appearance="outline"><mat-label>Status</mat-label><mat-select formControlName="status"><mat-option value="">All statuses</mat-option>@for(s of statuses;track s){<mat-option [value]="s">{{pretty(s)}}</mat-option>}</mat-select></mat-form-field></form>
<div class="table-card">@if(loading()){<mat-progress-bar mode="indeterminate"/>}<table mat-table [dataSource]="alerts()" matSort [matSortActive]="'riskScore'" [matSortDirection]="sortDirection()==='ASC'?'asc':'desc'" (matSortChange)="sort($event)">
<ng-container matColumnDef="alert"><th mat-header-cell *matHeaderCellDef>Alert</th><td mat-cell *matCellDef="let a"><strong>{{a.alertNumber}}</strong><small>{{a.transactionReference}}</small></td></ng-container>
<ng-container matColumnDef="customer"><th mat-header-cell *matHeaderCellDef>Customer</th><td mat-cell *matCellDef="let a"><strong>{{a.customerName}}</strong><small>{{a.customerNumber}}</small></td></ng-container>
<ng-container matColumnDef="severity"><th mat-header-cell *matHeaderCellDef>Severity</th><td mat-cell *matCellDef="let a"><span [class]="'badge sev-'+a.severity.toLowerCase()">{{a.severity}}</span></td></ng-container>
<ng-container matColumnDef="riskScore"><th mat-header-cell *matHeaderCellDef mat-sort-header>Risk score</th><td mat-cell *matCellDef="let a"><b>{{a.riskScore}}</b><small>{{a.riskBand}}</small></td></ng-container>
<ng-container matColumnDef="status"><th mat-header-cell *matHeaderCellDef>Status</th><td mat-cell *matCellDef="let a">{{pretty(a.status)}}</td></ng-container>
<ng-container matColumnDef="assignee"><th mat-header-cell *matHeaderCellDef>Assigned to</th><td mat-cell *matCellDef="let a">{{a.assignedToName||'Unassigned'}}</td></ng-container>
<ng-container matColumnDef="sla"><th mat-header-cell *matHeaderCellDef>SLA due</th><td mat-cell *matCellDef="let a"><span [class.overdue]="a.overdue">{{a.dueAt|date:'MMM d · HH:mm'}}</span><small>{{a.overdue?'Breached':'Within SLA'}}</small></td></ng-container>
<tr mat-header-row *matHeaderRowDef="columns"></tr><tr mat-row *matRowDef="let row;columns:columns" (click)="selected.set(row)"></tr></table>
<mat-paginator [length]="total()" [pageIndex]="page()" [pageSize]="size()" [pageSizeOptions]="[10,20,50]" (page)="paginate($event)"/></div></section>
@if(selected();as a){<div class="backdrop" (click)="selected.set(null)"></div><aside><header><div><p>ALERT REVIEW</p><h2>{{a.alertNumber}}</h2></div><button mat-button (click)="selected.set(null)">✕</button></header><main>
<div class="risk"><span [class]="'badge sev-'+a.severity.toLowerCase()">{{a.severity}}</span><strong>{{a.riskScore}}</strong><small>Risk score</small></div>
<dl><div><dt>Customer</dt><dd>{{a.customerName}}</dd></div><div><dt>Transaction</dt><dd>{{a.transactionReference}}</dd></div><div><dt>Status</dt><dd>{{pretty(a.status)}}</dd></div><div><dt>Assigned</dt><dd>{{a.assignedToName||'Unassigned'}}</dd></div></dl>
<section><h3>Alert summary</h3><p>{{a.alertSummary}}</p></section><footer><button mat-stroked-button (click)="action('assign')">Assign</button><button mat-stroked-button (click)="action('status')">Start review</button><button mat-flat-button color="primary" (click)="action('close')">Close alert</button></footer></main></aside>}
`,styles:[`header{display:flex;justify-content:space-between;margin-bottom:16px}header p{margin:0;color:#3169cb;font-size:.62rem;font-weight:750;letter-spacing:.13em}header span{color:#778398;font-size:.76rem}.page-title{margin:5px 0}.table-card,form{background:#fff;border:1px solid #e1e7ef;border-radius:11px}form{padding:12px;margin-bottom:12px}form mat-form-field{width:220px;margin-bottom:-20px}table{width:100%}th{background:#f8fafc!important;color:#748095;font-size:.65rem}td{font-size:.73rem}td strong,td small{display:block}td small{color:#8a95a6;margin-top:3px}.badge{padding:5px 8px;border-radius:20px;font-size:.61rem;font-weight:750}.sev-low{background:#e9f8f2;color:#157457}.sev-medium{background:#fff4da;color:#8f5d10}.sev-high{background:#ffe9dc;color:#ad4918}.sev-critical{background:#ffe5e8;color:#b4232d}.overdue{color:#c02e38;font-weight:750}tr[mat-row]{cursor:pointer}tr[mat-row]:hover{background:#f7faff}.backdrop{position:fixed;inset:0;z-index:40;background:#08152f60}aside{position:fixed;z-index:41;right:0;top:0;width:min(540px,94vw);height:100vh;background:#f7f9fc;box-shadow:-20px 0 60px #07142e40}aside>header{height:76px;padding:0 20px;margin:0;align-items:center;color:#fff;background:#0d1d43}aside header button{color:#fff}aside main{padding:18px}.risk,dl,aside section{background:#fff;border:1px solid #e1e7ef;border-radius:10px;padding:16px}.risk{display:grid;grid-template-columns:1fr auto}.risk strong{grid-row:span 2;font-size:2.2rem}.risk small{color:#8390a3}dl{display:grid;grid-template-columns:1fr 1fr;gap:14px}dt{color:#8390a3;font-size:.61rem}dd{margin:4px 0;font-size:.74rem;font-weight:650}aside section p{color:#627087;font-size:.7rem;line-height:1.6}footer{display:flex;gap:8px;justify-content:flex-end;margin-top:18px}`]})
export class AlertQueueComponent implements OnInit{private readonly service=inject(AlertService);private readonly fb=inject(FormBuilder);private readonly dialog=inject(MatDialog);private readonly destroy=inject(DestroyRef);private readonly reload$=new Subject<void>();
readonly statuses:AlertStatus[]=['NEW','ASSIGNED','IN_REVIEW','ESCALATED','CLOSED_FRAUD','CLOSED_FALSE_POSITIVE','CONVERTED_TO_CASE'];readonly columns=['alert','customer','severity','riskScore','status','assignee','sla'];readonly filters=this.fb.nonNullable.group({status:'' as AlertStatus|''});readonly alerts=signal<FraudAlert[]>([]);readonly total=signal(0);readonly page=signal(0);readonly size=signal(20);readonly sortDirection=signal<'ASC'|'DESC'>('DESC');readonly loading=signal(false);readonly selected=signal<FraudAlert|null>(null);
ngOnInit(){this.filters.valueChanges.pipe(takeUntilDestroyed(this.destroy)).subscribe(()=>{this.page.set(0);this.reload$.next()});this.reload$.pipe(switchMap(()=>this.load()),takeUntilDestroyed(this.destroy)).subscribe();this.reload$.next()}
private load(){this.loading.set(true);return this.service.list(this.filters.getRawValue().status,this.page(),this.size(),this.sortDirection()).pipe(tap(result=>{this.alerts.set(result.content);this.total.set(result.totalElements)}),finalize(()=>this.loading.set(false)));}
paginate(e:PageEvent){this.page.set(e.pageIndex);this.size.set(e.pageSize);this.reload$.next()}sort(e:Sort){if(e.active==='riskScore'){this.sortDirection.set(e.direction==='asc'?'ASC':'DESC');this.reload$.next()}}
action(mode:'assign'|'status'|'close'){const a=this.selected();if(!a)return;const source=mode==='assign'?this.service.assignees():of([]);source.pipe(switchMap(users=>this.dialog.open(AlertActionDialogComponent,{data:{mode,assignees:users}}).afterClosed()),filter(Boolean),switchMap(v=>mode==='assign'?this.service.assign(a.id,v.assignedTo,null):mode==='status'?this.service.updateStatus(a.id,v.status):this.service.close(a.id,v.status,v.resolution))).subscribe(updated=>{this.selected.set(updated);this.reload$.next()})}
pretty(v:string){return v.toLowerCase().split('_').map(p=>p[0]?.toUpperCase()+p.slice(1)).join(' ')}}
